# Generated by Django 5.0.1 on 2025-11-12 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: 住宅ローン、Netflix、ahamo', max_length=200, verbose_name='費目名')),
                ('category', models.CharField(choices=[('loan', 'ローン'), ('insurance', '保険'), ('subscription', 'サブスク'), ('utility', '光熱費'), ('communication', '通信費'), ('rent', '家賃'), ('other', 'その他固定費')], default='other', max_length=20, verbose_name='カテゴリ')),
                ('monthly_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='月額')),
                ('payment_date', models.IntegerField(blank=True, help_text='月の何日に支払うか', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='支払日')),
                ('is_loan', models.BooleanField(default=False, verbose_name='ローンか')),
                ('remaining_months', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='残回数')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, help_text='ローン完済日など', null=True, verbose_name='終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': '固定費',
                'verbose_name_plural': '固定費一覧',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(help_text='収入月（YYYY-MM-01形式）', verbose_name='年月')),
                ('category', models.CharField(choices=[('side_business', '事業所得'), ('rent_income', '家賃収入'), ('investment', '投資収入'), ('refund', '還付金'), ('bonus', '賞与'), ('temporary', '臨時収入'), ('other', 'その他')], max_length=20, verbose_name='カテゴリ')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='金額')),
                ('source', models.CharField(blank=True, help_text='例: ○○株式会社、マイニング、還付金', max_length=200, verbose_name='収入源')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='入金日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': '収入',
                'verbose_name_plural': '収入一覧',
                'ordering': ['-year_month', '-received_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyCashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(help_text='対象月（YYYY-MM-01形式）', unique=True, verbose_name='年月')),
                ('opening_balance', models.IntegerField(default=0, help_text='月初の残高', verbose_name='口座残高（期首）')),
                ('mid_month_balance', models.IntegerField(blank=True, default=0, verbose_name='口座残高（27日）')),
                ('closing_balance', models.IntegerField(default=0, help_text='月末の残高', verbose_name='口座残高（期末）')),
                ('monthly_change', models.IntegerField(default=0, help_text='期末 - 期首', verbose_name='月変動値')),
                ('savable_amount', models.IntegerField(default=0, verbose_name='預金可能額')),
                ('salary_net', models.IntegerField(default=0, help_text='SalaryRecordから自動取得', verbose_name='給与手取り')),
                ('bonus', models.IntegerField(default=0, verbose_name='賞与')),
                ('side_income', models.IntegerField(default=0, verbose_name='事業所得')),
                ('rent_income', models.IntegerField(default=0, verbose_name='家賃収入')),
                ('temporary_income', models.IntegerField(default=0, verbose_name='臨時収入')),
                ('refund', models.IntegerField(default=0, verbose_name='還付金')),
                ('other_income', models.IntegerField(default=0, verbose_name='その他収入')),
                ('total_income', models.IntegerField(default=0, verbose_name='収入合計')),
                ('housing_loan', models.IntegerField(default=0, verbose_name='住宅ローン')),
                ('other_loans', models.IntegerField(default=0, verbose_name='その他ローン')),
                ('insurance', models.IntegerField(default=0, verbose_name='保険料')),
                ('subscription', models.IntegerField(default=0, verbose_name='サブスク')),
                ('utilities', models.IntegerField(default=0, verbose_name='光熱費')),
                ('communication', models.IntegerField(default=0, verbose_name='通信費')),
                ('rent', models.IntegerField(default=0, verbose_name='家賃')),
                ('total_fixed_expense', models.IntegerField(default=0, verbose_name='固定費合計')),
                ('credit_card_payments', models.JSONField(default=dict, help_text="{'カード名': 金額}", verbose_name='クレカ引落')),
                ('total_credit_payment', models.IntegerField(default=0, verbose_name='クレカ合計')),
                ('food', models.IntegerField(default=0, verbose_name='食費')),
                ('daily_goods', models.IntegerField(default=0, verbose_name='日用品')),
                ('clothing', models.IntegerField(default=0, verbose_name='衣服美容')),
                ('social', models.IntegerField(default=0, verbose_name='交際費')),
                ('transport', models.IntegerField(default=0, verbose_name='交通費')),
                ('medical', models.IntegerField(default=0, verbose_name='医療費')),
                ('education', models.IntegerField(default=0, verbose_name='教養・教育')),
                ('entertainment', models.IntegerField(default=0, verbose_name='趣味娯楽')),
                ('other_variable', models.IntegerField(default=0, verbose_name='その他変動費')),
                ('total_variable_expense', models.IntegerField(default=0, verbose_name='変動費合計')),
                ('total_expense', models.IntegerField(default=0, help_text='固定費 + クレカ + 変動費', verbose_name='支出総額')),
                ('net_cashflow', models.IntegerField(default=0, help_text='収入 - 支出', verbose_name='純キャッシュフロー')),
                ('risk_level', models.CharField(choices=[('safe', '安全'), ('warning', '注意'), ('danger', '危険')], default='safe', max_length=10, verbose_name='リスクレベル')),
                ('risk_message', models.TextField(blank=True, verbose_name='リスクメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': '月次キャッシュフロー',
                'verbose_name_plural': '月次キャッシュフロー一覧',
                'ordering': ['-year_month'],
            },
        ),
        migrations.CreateModel(
            name='VariableExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(help_text='支出月（YYYY-MM-01形式）', verbose_name='年月')),
                ('category', models.CharField(choices=[('food', '食費'), ('daily_goods', '日用品'), ('clothing', '衣服美容'), ('social', '交際費'), ('transport', '交通費'), ('medical', '医療費'), ('education', '教養・教育'), ('entertainment', '趣味娯楽'), ('other', 'その他')], max_length=20, verbose_name='カテゴリ')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='金額')),
                ('expense_date', models.DateField(blank=True, null=True, verbose_name='支出日')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': '変動費',
                'verbose_name_plural': '変動費一覧',
                'ordering': ['-year_month', '-expense_date'],
            },
        ),
    ]
