# Generated by Django 5.0.1 on 2025-11-12 15:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: 楽天カード、三井住友カード', max_length=100, verbose_name='カード名')),
                ('card_number_last4', models.CharField(blank=True, help_text='識別用', max_length=4, verbose_name='カード番号下4桁')),
                ('closing_date', models.IntegerField(help_text='月の何日締めか（例：15日締めなら15）', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='締め日')),
                ('payment_date', models.IntegerField(help_text='月の何日引落か（例：10日引落なら10）', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='引落日')),
                ('bank_account', models.CharField(blank=True, help_text='例: みずほ銀行 普通預金', max_length=100, verbose_name='引落口座')),
                ('credit_limit', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='利用限度額')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': 'クレジットカード',
                'verbose_name_plural': 'クレジットカード一覧',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(help_text='支払い月（YYYY-MM-01形式）', unique=True, verbose_name='年月')),
                ('credit_card_payments', models.JSONField(default=dict, help_text="{'カード名': 金額} の辞書", verbose_name='クレカ引落予定')),
                ('total_credit_payment', models.IntegerField(default=0, verbose_name='クレカ合計')),
                ('loan_payments', models.JSONField(default=dict, help_text="{'ローン名': 金額} の辞書", verbose_name='ローン支払予定')),
                ('total_loan_payment', models.IntegerField(default=0, verbose_name='ローン合計')),
                ('total_payment', models.IntegerField(default=0, help_text='クレカ + ローンの合計', verbose_name='支払総額')),
                ('risk_level', models.CharField(choices=[('safe', '安全'), ('warning', '注意'), ('danger', '危険')], default='safe', max_length=10, verbose_name='リスクレベル')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': '支払いスケジュール',
                'verbose_name_plural': '支払いスケジュール一覧',
                'ordering': ['-year_month'],
            },
        ),
        migrations.CreateModel(
            name='ShortTermLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: iPhone 15 分割、ドコモ光工事費', max_length=100, verbose_name='ローン名')),
                ('monthly_payment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='月額支払額')),
                ('remaining_months', models.IntegerField(help_text='残り何ヶ月か', validators=[django.core.validators.MinValueValidator(0)], verbose_name='残回数')),
                ('payment_date', models.IntegerField(help_text='月の何日引落か', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='引落日')),
                ('start_date', models.DateField(help_text='ローン開始日', verbose_name='開始日')),
                ('bank_account', models.CharField(blank=True, max_length=100, verbose_name='引落口座')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': '短期ローン',
                'verbose_name_plural': '短期ローン一覧',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField(verbose_name='利用日')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='利用金額')),
                ('merchant', models.CharField(blank=True, max_length=200, verbose_name='利用店舗')),
                ('category', models.CharField(choices=[('food', '食費'), ('transport', '交通費'), ('utility', '光熱費'), ('communication', '通信費'), ('shopping', '買い物'), ('entertainment', '娯楽'), ('medical', '医療'), ('other', 'その他')], default='other', max_length=20, verbose_name='カテゴリ')),
                ('payment_date', models.DateField(blank=True, help_text='自動計算される', null=True, verbose_name='引落予定日')),
                ('is_paid', models.BooleanField(default=False, verbose_name='支払済み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.creditcard', verbose_name='クレジットカード')),
            ],
            options={
                'verbose_name': 'クレジットカード利用明細',
                'verbose_name_plural': 'クレジットカード利用明細一覧',
                'ordering': ['-usage_date'],
            },
        ),
    ]
