# Generated by Django 5.0.1 on 2025-11-12 14:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(help_text='給与支給月（YYYY-MM-01形式）', unique=True, verbose_name='年月')),
                ('base_salary', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='基本給')),
                ('position_allowance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='役職手当')),
                ('qualification_allowance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='資格手当')),
                ('store_qualification_allowance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='店舗資格手当')),
                ('pharmacist_regional_allowance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='薬剤師地区手当')),
                ('relocation_allowance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='転勤手当')),
                ('housing_allowance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='住宅手当')),
                ('adjustment_allowance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='調整手当')),
                ('family_allowance', models.IntegerField(default=0, help_text='2万～3.5万', validators=[django.core.validators.MinValueValidator(0)], verbose_name='家族手当')),
                ('base_hourly_wage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='基本時給')),
                ('overtime_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='時間外労働時間（分）')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='自動計算：分÷60', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='時間外労働時間（時間）')),
                ('overtime_pay', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='時間外手当')),
                ('night_work_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='深夜手当（分）')),
                ('night_work_pay', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='深夜手当')),
                ('holiday_work_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='休日出勤時間')),
                ('holiday_work_pay', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='休日出勤手当')),
                ('parking_fee', models.IntegerField(default=0, verbose_name='駐車場代')),
                ('commuting_allowance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='通勤手当')),
                ('taxable_commuting_allowance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='課税通勤手当')),
                ('payment_adjustment', models.IntegerField(default=0, verbose_name='支給精算')),
                ('taxable_payment', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='課税支給')),
                ('total_payment', models.IntegerField(default=0, help_text='自動計算：全支給項目の合計', verbose_name='支給総額')),
                ('dependent_family_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='扶養家族')),
                ('insurance_standard_salary', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='保険標準報酬額')),
                ('health_insurance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='健康保険')),
                ('fire_insurance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='火災保険')),
                ('pension_insurance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='厚生年金')),
                ('employment_insurance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='雇用保険')),
                ('matching_contribution', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='マッチング拠出金')),
                ('taxable_amount', models.IntegerField(default=0, help_text='自動計算', verbose_name='課税対象額')),
                ('monthly_income_tax', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='月次所得税')),
                ('resident_tax', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='住民税')),
                ('mutual_aid', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='共済会')),
                ('union_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='組合費')),
                ('damage_insurance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='損害保険')),
                ('ltd_insurance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='LTD保険')),
                ('company_housing_deduction', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='借上社宅控除')),
                ('year_end_adjustment', models.IntegerField(default=0, verbose_name='年末調整')),
                ('total_deduction', models.IntegerField(default=0, help_text='自動計算：全控除項目の合計', verbose_name='控除合計')),
                ('actual_payment', models.IntegerField(default=0, help_text='自動計算：支給総額 - 控除合計', verbose_name='実支給額')),
                ('net_payment', models.IntegerField(default=0, help_text='実支給額と同じ', verbose_name='差引支給額')),
                ('difference', models.IntegerField(default=0, help_text='実支給額 - 差引支給額（通常0）', verbose_name='差額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': '給与明細',
                'verbose_name_plural': '給与明細一覧',
                'ordering': ['-year_month'],
            },
        ),
    ]
