# Generated by Django 5.0.1 on 2025-11-12 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: みずほ銀行普通預金、楽天証券、自宅マンション', max_length=200, verbose_name='資産名')),
                ('category', models.CharField(choices=[('cash', '現金'), ('bank', '預金'), ('investment', '投資'), ('real_estate', '不動産'), ('vehicle', '車両'), ('other', 'その他資産')], max_length=20, verbose_name='カテゴリ')),
                ('current_value', models.IntegerField(help_text='最新の評価額', validators=[django.core.validators.MinValueValidator(0)], verbose_name='現在価値')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='取得日')),
                ('acquisition_cost', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='取得原価')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('account_number', models.CharField(blank=True, max_length=100, verbose_name='口座番号・識別番号')),
                ('institution', models.CharField(blank=True, help_text='例: みずほ銀行、楽天証券', max_length=100, verbose_name='金融機関・管理会社')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': '資産',
                'verbose_name_plural': '資産一覧',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: フラット35住宅ローン、三井住友カードローン', max_length=200, verbose_name='負債名')),
                ('category', models.CharField(choices=[('housing_loan', '住宅ローン'), ('car_loan', '自動車ローン'), ('card_loan', 'カードローン'), ('student_loan', '奨学金'), ('personal_loan', '個人借入'), ('other', 'その他負債')], max_length=20, verbose_name='カテゴリ')),
                ('current_balance', models.IntegerField(help_text='最新の残債額', validators=[django.core.validators.MinValueValidator(0)], verbose_name='現在残高')),
                ('original_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='借入総額')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='年利', max_digits=5, null=True, verbose_name='金利（%）')),
                ('monthly_payment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='月額返済額')),
                ('remaining_months', models.IntegerField(help_text='残り何ヶ月か', validators=[django.core.validators.MinValueValidator(0)], verbose_name='残回数')),
                ('start_date', models.DateField(verbose_name='借入開始日')),
                ('maturity_date', models.DateField(blank=True, null=True, verbose_name='完済予定日')),
                ('payment_date', models.IntegerField(help_text='月の何日に返済するか', validators=[django.core.validators.MinValueValidator(1)], verbose_name='返済日')),
                ('lender', models.CharField(help_text='例: みずほ銀行、住宅金融支援機構', max_length=100, verbose_name='貸主・金融機関')),
                ('account_number', models.CharField(blank=True, max_length=100, verbose_name='口座番号・契約番号')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': '負債',
                'verbose_name_plural': '負債一覧',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(help_text='対象月（YYYY-MM-01形式）', unique=True, verbose_name='年月')),
                ('cash', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='現金')),
                ('bank_deposits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='預金')),
                ('current_assets', models.IntegerField(default=0, verbose_name='流動資産合計')),
                ('stocks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='株式')),
                ('bonds', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='債券')),
                ('investment_trusts', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='投資信託')),
                ('crypto', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='暗号資産')),
                ('investment_assets', models.IntegerField(default=0, verbose_name='投資資産合計')),
                ('real_estate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='不動産')),
                ('vehicles', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='車両')),
                ('other_assets', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='その他資産')),
                ('fixed_assets', models.IntegerField(default=0, verbose_name='固定資産合計')),
                ('total_assets', models.IntegerField(default=0, verbose_name='資産合計')),
                ('credit_card_debt', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='クレジットカード債務')),
                ('short_term_loans', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='短期ローン')),
                ('current_liabilities', models.IntegerField(default=0, verbose_name='短期負債合計')),
                ('housing_loan', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='住宅ローン')),
                ('car_loan', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='自動車ローン')),
                ('student_loan', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='奨学金')),
                ('other_loans', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='その他ローン')),
                ('long_term_liabilities', models.IntegerField(default=0, verbose_name='長期負債合計')),
                ('total_liabilities', models.IntegerField(default=0, verbose_name='負債合計')),
                ('net_worth', models.IntegerField(default=0, help_text='資産合計 - 負債合計', verbose_name='純資産')),
                ('net_worth_change', models.IntegerField(default=0, help_text='前月との差額', verbose_name='純資産増減')),
                ('net_worth_change_ratio', models.DecimalField(decimal_places=2, default=0, help_text='前月比の変動率', max_digits=5, verbose_name='純資産増減率（%）')),
                ('debt_ratio', models.DecimalField(decimal_places=2, default=0, help_text='負債 / 資産 × 100', max_digits=5, verbose_name='負債比率（%）')),
                ('liquidity_ratio', models.DecimalField(decimal_places=2, default=0, help_text='流動資産 / 短期負債 × 100', max_digits=5, verbose_name='流動比率（%）')),
                ('financial_health', models.CharField(choices=[('excellent', '非常に良好'), ('good', '良好'), ('fair', '普通'), ('warning', '注意'), ('danger', '危険')], default='fair', max_length=10, verbose_name='財務健全性')),
                ('health_message', models.TextField(blank=True, verbose_name='健全性メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': '月次バランスシート',
                'verbose_name_plural': '月次バランスシート一覧',
                'ordering': ['-year_month'],
            },
        ),
    ]
